spring:
  application:
    name: back-intro
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  port: ${SERVER_PORT:8081}

security:
  jwt:
    issuer: ${JWT_ISSUER:back-intro}
    secret: ${JWT_SECRET}
    access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:900000}
    refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800000}
