CREATE TABLE ${db_schema}.mental_status_exams (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    encounter_id UUID NOT NULL,
    appearance TEXT,
    behavior TEXT,
    attitude TEXT,
    consciousness TEXT,
    orientation TEXT,
    attention TEXT,
    memory TEXT,
    speech TEXT,
    mood TEXT,
    affect TEXT,
    thought_process TEXT,
    thought_content TEXT,
    perception TEXT,
    judgment TEXT,
    insight TEXT,
    psychomotor_activity TEXT,
    observations TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by UUID,
    CONSTRAINT fk_mental_status_exams_encounter FOREIGN KEY (encounter_id) REFERENCES ${db_schema}.encounters(id) ON DELETE CASCADE,
    CONSTRAINT fk_mental_status_exams_created_by FOREIGN KEY (created_by) REFERENCES ${db_schema}.professionals(id),
    CONSTRAINT uk_mental_status_exams_encounter UNIQUE (encounter_id)
);
